*This part includes data cleansing and data manipulation operations on the dataset. Firstly, v1 column was renamed as index, as it gives more clarity. Since there are NA-s in different columns, they are handled differently for numeric and strings types. To further analyze data correctly, I decided to drop observations with missing values of "price" and "odometer". For the rest of columns, missing values were renamed as Unknown, since it can be categorized. Next, I deleted currency symbol of price and made it into numeric. New column "year" was generated by extracting value from column "name", on which also other data manipulation was done. Columns "odometer" and "year" were also destringed. 

rename v1 index
misstable summarize
drop if price == "NA" | odometer == "NA"
replace area = "Unknown" if area == "NA"
replace subarea = "Unknown" if subarea == "NA"
replace name = "Unknown" if name == "NA"
replace condition = "Unknown" if condition == "NA"
replace cylinders = "Unknown" if cylinders == "NA"
replace drive = "Unknown" if drive == "NA"
replace fuel = "Unknown" if fuel == "NA"
replace paintcolor = "Unknown" if paintcolor == "NA"
replace size = "Unknown" if size == "NA"
replace transmission = "Unknown" if transmission == "NA"
replace type = "Unknown" if type == "NA"
describe
summarize

replace price = substr(price, 2, .)
generate year = substr(name, 1, 4)
replace name = substr(name, 5, .)
replace name = trim(name)
replace name = stritrim(name)
replace name = lower(name)

destring price, replace
destring odometer, replace ignore(",")
destring year, replace